### ISSUE TITLE
Add floating TOC on right side of content

### ISSUE THREAD

**Issue by embik** [kubermatic/docs#1150]
After some [user feedback](https://github.com/kubermatic/dashboard/issues/4737#issuecomment-1210599173) on our docs, I discussed having a floating TOC with @cschieder and we agreed this might be useful. This can help users discover content on a page (we don't always set `enableTOC` on our pages and that is only at the top of a page anyway) and improve orientation/navigation while going over a longer document. Usually, this "floating TOC" is on the right side of the actual content and frames it together with the navigation on the left.

Examples for this kind of "floating TOC" (not sure if this is the proper web development term for it) are the AWS docs, for example [this page](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html). Kubernetes [also does it](https://kubernetes.io/docs/concepts/overview/what-is-kubernetes/).

Ideally, this would:

- Highlight the section that a user is currently looking at
- Be collapsible, so users can focus on the content if they don't need the additional navigation help
- Maybe not show for pages that don't have additional headlines (minor/small pages)

But those are all "nice to have" in my view and not required.

**Comment by embik** [comment]
@serg any thoughts on this? Is it doable for us and how complex would it be?

**Comment by almereyda** [comment]
To second the OP, this will be really useful for lengthy, hierarchically ordered documents. Especially the headline level formatting is sometimes too similar to see real differences, and without visible breadcrumbs or numbered headlines, it's often hard to depict to which section a piece of text belongs.

**Comment by serg** [comment]
TOC sidebar was implemented in [PR#1294](https://github.com/kubermatic/docs/pull/1294).
@cschieder, @embik, @almereyda please have a look on how it works [here](https://deploy-preview-1294--cranky-newton-4e6ed2.netlify.app/) and let me know your feedback.

**Comment by embik** [comment]
@serg I absolutely love it! I was wondering if it would look better without the "Table of Content" header, but I'm not really sure. But it looks great in any case! Thanks so much for implementing this.

**Comment by almereyda** [comment]
Indeed, it looks beautiful.

To second the comment about **Table Of Content**, I believe in native English it'd read *Table of contents*, but more precisely—and because the list of other documentation on the left side could also be perceived as a "Table of Contents"—a wording like *Contents on this page*, *Contents* or *On this page* could easy the understanding a bit (about where we are, referring to my comment https://github.com/kubermatic/dashboard/issues/4737#issuecomment-1210599173 from the OP).

If a CSS Ninja came around, I think it would be cool to have this shown at the top on short and long pages alike, but could scroll away with the page content, to declutter the reading view for longer sessions that need more attention. (Still we cannot fold the left sidebar, but that's another issue.)

Thank you for picking up on this, it is much appreciated, esp. since most of my other (documentation) issues got stale without comment and just closed themselves. That felt a little deliberating, but now it's good to see that feedback from the community is well received and can also have little influence.

**Comment by embik** [comment]
@almereyda very sorry about your other issues closing without any feedback. I'll follow up on them.

**Comment by almereyda** [comment]
Thank you! It's always good when we're talking (: I thought they were passed on into some internal issue tracker, or just overlooked, so no hard feelings here.
